"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { AppNav } from "@/components/app/AppNav";
import { missions } from "@/lib/engine/catalog";
import { useProgress } from "@/lib/client/progress";
import type { CommerceProduct } from "@/lib/integrations/commerce";

const fallbackProducts = [
  ...missions.map((m,i)=>({ id:m.id, entitlement:m.requiredEntitlement, title:m.title, type:"Mission", price:[1900,2900,3900][i], currency:"eur", subtitle:m.outcome })),
  { id:"field-notes", entitlement:"library:platform-engineering", title:"Platform Engineering Field Notes", type:"Digital book", price:2400, currency:"eur", subtitle:"Operational patterns, checklists and troubleshooting recipes consumed by the CPL knowledge layer." },
];
function money(amount?: number, currency="eur") { return amount == null ? "—" : new Intl.NumberFormat("en",{style:"currency",currency:currency.toUpperCase()}).format(amount/100); }

export default function StorePage(){
  const {progress,unlock}=useProgress(); const [remote,setRemote]=useState<CommerceProduct[]>([]); const [medusa,setMedusa]=useState(false); const [error,setError]=useState(""); const [cartId,setCartId]=useState(""); const [commerceMessage,setCommerceMessage]=useState(""); const [busy,setBusy]=useState("");
  useEffect(()=>{fetch("/api/commerce/products").then(r=>r.json()).then(data=>{setMedusa(Boolean(data.configured));setRemote(data.products||[]);setError(data.error||"");}).catch(()=>{});},[]);
  const products = remote.length ? remote.map(p=>({...p,type:"Medusa product",subtitle:p.subtitle||"Commerce product",entitlement:p.entitlement})) : fallbackProducts;
  const addToCart=async(product:any)=>{if(!product.variantId)return;setBusy(product.id);setCommerceMessage("");try{const r=await fetch("/api/commerce/cart",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({cartId:cartId||undefined,variantId:product.variantId})});const data=await r.json();if(!r.ok)throw new Error(data.error||"cart error");setCartId(data.cartId);setCommerceMessage(`Cart ${data.cartId.slice(-8)} ready. ${product.title} added.`);}catch(e){setCommerceMessage(e instanceof Error?e.message:"cart error");}finally{setBusy("");}};
  const complete=async()=>{if(!cartId)return;setBusy("checkout");try{const r=await fetch("/api/commerce/cart/complete",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({cartId})});const data=await r.json();if(!r.ok)throw new Error(data.error||"checkout error");if(data.type==="order")setCommerceMessage(`Order ${data.order?.id||"placed"} created. Medusa order.placed will grant CPL access.`);else setCommerceMessage(data.error?.message||"Cart requires the remaining Medusa checkout/payment steps.");}catch(e){setCommerceMessage(e instanceof Error?e.message:"checkout error");}finally{setBusy("");}};
  return <main className="app-shell"><AppNav/><section className="catalog-page"><div className="catalog-head"><div><span className="section-kicker">{medusa?"MEDUSA LIVE":"COMMERCE ADAPTER"}</span><h1>Library & access.</h1><p>{medusa?"Live Store API. Cart line items carry the Clerk identity; order.placed is normalized into an idempotent CPL entitlement.":"Add Medusa env vars and this page switches from the local catalog to the live Store API without changing learning code."}</p>{error&&<small className="integration-error">{error}</small>}{commerceMessage&&<small className="commerce-message">{commerceMessage}</small>}</div>{medusa&&cartId&&<div className="cart-state"><small>ACTIVE CART</small><strong>…{cartId.slice(-10)}</strong><button onClick={complete} disabled={busy==="checkout"}>{busy==="checkout"?"Completing…":"Complete cart →"}</button></div>}</div><div className="store-grid">{products.map((p:any)=>{const key=p.entitlement;const owned=key?progress.entitlements.includes(key):false;return <article key={p.id}><div className="product-type">{p.type}</div><h2>{p.title}</h2><p>{p.subtitle}</p><div className="product-bottom"><strong>{money(p.price,p.currency)}</strong>{owned?<span className="owned-chip">OWNED</span>:medusa&&p.variantId?<button disabled={busy===p.id} onClick={()=>addToCart(p)}>{busy===p.id?"Adding…":"Add to cart →"}</button>:!medusa&&key?<button onClick={()=>unlock(key)}>Demo unlock →</button>:<span className="owned-chip">NO VARIANT</span>}</div></article>})}</div><div className="commerce-note"><div><small>PRODUCTION FLOW</small><strong>Clerk → Medusa cart → payment/complete → order.placed → CPL entitlement</strong></div><Link href="/missions">Back to missions →</Link></div></section></main>;
}
