"use client";

import Link from "next/link";
import { Suspense, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { Brand } from "@/components/Brand";
import { useProgress } from "@/lib/client/progress";
import type { MissionDefinition } from "@/lib/engine/types";

type Plan = { missionId:string; confidence:number; entryMode:"guided"|"challenge"; rationale:string; skillGaps:Array<{id:string;label:string;current:number;target:number;gap:number}>; missingPrerequisites:Array<{id:string;label:string;current:number}>; alternatives:Array<{missionId:string;title:string;score:number}>; mission:MissionDefinition };
const roles=["Platform Engineer","SRE","DevOps","Cloud Engineer"];
const levels:["new"|"hands-on"|"production",string,string][]=[["new","New to this","Teach foundations only when needed"],["hands-on","Hands-on","I’ve built things, now make me reliable"],["production","Production","Challenge me before explaining"]];

function StartContent(){
 const params=useSearchParams(); const {progress,hydrated}=useProgress(); const [goal,setGoal]=useState(params.get("goal")||"Deploy a production-ready Kubernetes application"); const [role,setRole]=useState("Platform Engineer"); const [experience,setExperience]=useState<"new"|"hands-on"|"production">("hands-on"); const [plan,setPlan]=useState<Plan|null>(null); const [busy,setBusy]=useState(false);
 const build=async()=>{setBusy(true);try{const r=await fetch("/api/plan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({goal,role,experience,mastery:progress.skillMastery,completedMissions:progress.completedMissions})});const data=await r.json();if(r.ok)setPlan(data);}finally{setBusy(false);}};
 useEffect(()=>{if(hydrated)build();},[hydrated]);
 return <main className="start-shell"><header className="start-nav"><Link href="/"><Brand/></Link><span>GOAL INTAKE / SKILL GAP PLANNER</span><Link href="/dashboard">Command Center ↗</Link></header><section className="start-grid"><div className="intake-pane"><span className="section-kicker">01 / INTENT</span><h1>What must you be<br/><em>able to do?</em></h1><label>Outcome<input value={goal} onChange={e=>setGoal(e.target.value)} /></label><label>Target role<div className="choice-grid">{roles.map(r=><button className={role===r?"active":""} onClick={()=>setRole(r)} key={r}>{r}</button>)}</div></label><label>Current operating level<div className="level-stack">{levels.map(([id,title,desc])=><button className={experience===id?"active":""} onClick={()=>setExperience(id)} key={id}><b>{title}</b><span>{desc}</span></button>)}</div></label><button className="replan-button" onClick={build} disabled={busy}>{busy?"Recompiling graph…":"Recompile my plan →"}</button></div><div className="briefing-pane">{!plan?<div className="plan-loading"><i/><strong>Reading skill graph…</strong><span>goal → prerequisites → gaps → evidence path</span></div>:<><div className="briefing-head"><div><span className="section-kicker">02 / MISSION BRIEF</span><h2>{plan.mission.title}</h2><p>{plan.rationale}</p></div><div className="confidence-ring"><strong>{Math.round(plan.confidence*100)}</strong><span>match</span></div></div><div className="plan-meta"><div><small>ENTRY MODE</small><strong>{plan.entryMode}</strong></div><div><small>DIFFICULTY</small><strong>{plan.mission.difficulty}</strong></div><div><small>DURATION</small><strong>{plan.mission.duration}</strong></div></div><div className="gap-block"><div className="gap-title"><span>SKILL GAPS</span><b>{plan.skillGaps.length} signals</b></div>{plan.skillGaps.map(g=><div className="gap-row" key={g.id}><span>{g.label}</span><i><em style={{width:`${Math.round(g.current*100)}%`}}/><b style={{left:`${Math.round(g.target*100)}%`}}/></i><strong>{Math.round(g.current*100)} → {Math.round(g.target*100)}</strong></div>)}</div>{plan.missingPrerequisites.length>0&&<div className="prereq-box"><small>PREREQUISITES TO WATCH</small>{plan.missingPrerequisites.map(p=><span key={p.id}>{p.label} <b>{Math.round(p.current*100)}%</b></span>)}</div>}<div className="briefing-outcome"><small>PROOF TARGET</small><strong>{plan.mission.outcome}</strong></div><Link className="launch-plan" href={`/workspace?mission=${plan.missionId}&goal=${encodeURIComponent(goal)}&mode=${plan.entryMode}`}>Launch {plan.entryMode} mission <span>→</span></Link><div className="alternate-plans"><span>ALTERNATIVES</span>{plan.alternatives.map(a=><Link href={`/workspace?mission=${a.missionId}&goal=${encodeURIComponent(goal)}`} key={a.missionId}>{a.title} ↗</Link>)}</div></>}</div></section></main>;
}
export default function StartPage(){return <Suspense fallback={<main className="start-shell"/>}><StartContent/></Suspense>}
